version: "3.7"

services:
  app:
    build: .
    container_name: Nebulosa
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    networks:
      - app-network
    links:
      - databaseNebulosa
    depends_on:
      - databaseNebulosa
      - mongoNebulosa

  databaseNebulosa:
    image: postgres
    container_name: databaseNebulosa
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=nebulosa
      - POSTGRES_DB=nebulosa
    volumes:
      - pgdata:/data/postgres
    networks:
      - app-network

  mongoNebulosa:
    image: mongo:latest
    container_name: mongoNebulosa
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/mongo
    networks:
      - app-network

volumes:
  pgdata:
    driver: local
  mongodata:
    driver: local

networks:
  app-network:
    driver: bridge
