version: '3.7'

services:
  databaseNebulosa:
    image: postgres
    container_name: databaseNebulosa
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=nebulosa
      - POSTGRES_DB=nebulosa
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: Nebulosa
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - databaseNebulosa
    depends_on:
      - databaseNebulosa

volumes:
  pgdata:
    driver: local
